### ISSUE TITLE
Display Year and Edition information in the Main page.

### ISSUE THREAD

**Issue by omaciel** [AFistfulOfLinks/afistfuloflinks#14]
**Describe the solution you'd like**
Display the **Year** and **Edition** for any given post in the main page.

**Additional context**
I thought that maybe displaying the year and edition information directly underneath the post's name would be "interesting" to show though I'm not sure if it would be useful.

Take a look at the **first** and **second** post entries in the screenshot below for two examples:

<img width="891" alt="Screen Shot 2020-08-11 at 12 31 27 PM" src="https://user-images.githubusercontent.com/53362/89923776-15e0f900-dbcf-11ea-9d79-42588ca7b3c5.png">

The proposed patch would be:

```diff
diff --git a/layouts/index.html b/layouts/index.html
index b5721bf..bcb2f71 100644
--- a/layouts/index.html
+++ b/layouts/index.html
@@ -14,6 +14,16 @@
 </div>
 <div class="matter">
 <h3 class="title small"><a href="{{ .RelPermalink }}">{{.Title}}{{ if .Draft }}<sup class="draft-label">DRAFT</sup>{{ end }}</a></h3>
+<p class="edition">
+    Year:
+    {{ if isset .Params "year" }}
+    {{ .Page.Params.year }}
+    {{ end }}
+    Edition:
+    {{ if isset .Params "edition" }}
+    {{ .Page.Params.edition }}
+    {{ end }}
+<p>
 <span class="description">
 {{ if isset .Params "description" }}
 {{ .Description }}
```diff

Additional changes to the `css` would be required to create a different rule for `p.edition`.

**Comment by omaciel** [comment]
@mirekdlugosz thoughts?

**Comment by mirekdlugosz** [comment]
@omaciel Personally, I probably won't find that useful, but since you have thought about this and implemented early version, I'm sure it's useful for **you**. So yeah, I think we could add something like that.

Just two things:
1. I would probably try to make "year - edition" look exactly the same on posts listing and on single post page. It might make sense to implement it as partial template, that would be included/called in two different places.
2. I think we could drop checking if "year" and "edition" are set, since all posts require that metadata, and this template file is only ever used to display posts list (or so I believe).

**Comment by omaciel** [comment]
> 1. I would probably try to make "year - edition" look exactly the same on posts listing and on single post page. It might make sense to implement it as partial template, that would be included/called in two different places.

I see. Take a look at what the default style looks like below. Please note that we should change the style for post listing to help with the right alignment.

<img width="877" alt="Screen Shot 2020-08-12 at 2 22 26 PM" src="https://user-images.githubusercontent.com/53362/90052730-92470b00-dca7-11ea-8760-94b5e133e3e1.png">

> 2. I think we could drop checking if "year" and "edition" are set, since all posts require that metadata, and this template file is only ever used to display posts list (or so I believe).

ack

I can have a PR ready soon.

**Comment by mirekdlugosz** [comment]
Closing, as https://github.com/AFistfulOfLinks/hugo-vitae-afol/pull/4 and #17 are now merged (thought github will close that automatically, but apparently it does not)
